# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChaosScenario(BaseModel):
    """
    ChaosScenario
    """ # noqa: E501
    name: StrictStr
    description: Optional[StrictStr] = None
    organisation: Optional[CreateAccessReviewRequestDataReviewer] = None
    target_service: StrictStr
    chaos_type: StrictStr
    duration_seconds: Optional[StrictInt] = None
    intensity: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    result_summary: Optional[StrictStr] = None
    started_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    expected_behavior: Optional[StrictStr] = None
    actual_behavior: Optional[StrictStr] = None
    passed: Optional[StrictBool] = None
    __properties: ClassVar[List[str]] = ["name", "description", "organisation", "target_service", "chaos_type", "duration_seconds", "intensity", "status", "result_summary", "started_at", "completed_at", "expected_behavior", "actual_behavior", "passed"]

    @field_validator('chaos_type')
    def chaos_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['pod_kill', 'network_partition', 'cpu_stress', 'disk_fill', 'latency_inject', 'memory_pressure']):
            raise ValueError("must be one of enum values ('pod_kill', 'network_partition', 'cpu_stress', 'disk_fill', 'latency_inject', 'memory_pressure')")
        return value

    @field_validator('intensity')
    def intensity_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['draft', 'running', 'completed', 'failed', 'cancelled']):
            raise ValueError("must be one of enum values ('draft', 'running', 'completed', 'failed', 'cancelled')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChaosScenario from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChaosScenario from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "target_service": obj.get("target_service"),
            "chaos_type": obj.get("chaos_type"),
            "duration_seconds": obj.get("duration_seconds"),
            "intensity": obj.get("intensity"),
            "status": obj.get("status"),
            "result_summary": obj.get("result_summary"),
            "started_at": obj.get("started_at"),
            "completed_at": obj.get("completed_at"),
            "expected_behavior": obj.get("expected_behavior"),
            "actual_behavior": obj.get("actual_behavior"),
            "passed": obj.get("passed")
        })
        return _obj


