# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class ChaosMonkey(BaseModel):
    """
    ChaosMonkey
    """ # noqa: E501
    name: StrictStr
    experiment_type: StrictStr
    target_service: StrictStr
    enabled: Optional[StrictBool] = None
    schedule: Optional[StrictStr] = None
    duration_seconds: Optional[StrictInt] = None
    blast_radius: Optional[StrictStr] = None
    last_run_at: Optional[datetime] = None
    last_result: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["name", "experiment_type", "target_service", "enabled", "schedule", "duration_seconds", "blast_radius", "last_run_at", "last_result", "notes"]

    @field_validator('experiment_type')
    def experiment_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['latency_injection', 'error_rate_spike', 'resource_exhaustion', 'dependency_failure', 'network_partition']):
            raise ValueError("must be one of enum values ('latency_injection', 'error_rate_spike', 'resource_exhaustion', 'dependency_failure', 'network_partition')")
        return value

    @field_validator('blast_radius')
    def blast_radius_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['single', 'zone', 'region']):
            raise ValueError("must be one of enum values ('single', 'zone', 'region')")
        return value

    @field_validator('last_result')
    def last_result_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['success', 'aborted', 'failed']):
            raise ValueError("must be one of enum values ('success', 'aborted', 'failed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChaosMonkey from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChaosMonkey from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "experiment_type": obj.get("experiment_type"),
            "target_service": obj.get("target_service"),
            "enabled": obj.get("enabled"),
            "schedule": obj.get("schedule"),
            "duration_seconds": obj.get("duration_seconds"),
            "blast_radius": obj.get("blast_radius"),
            "last_run_at": obj.get("last_run_at"),
            "last_result": obj.get("last_result"),
            "notes": obj.get("notes")
        })
        return _obj


