# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CloudAsset(BaseModel):
    """
    CloudAsset
    """ # noqa: E501
    external_id: StrictStr = Field(description="Provider-native resource identifier (e.g. i-abc123, /subscriptions/.../resourceGroups/..., projects/.../instances/...). Unique together with `credential`.")
    credential_external_id_key: Optional[StrictStr] = Field(default=None, description="Denormalizovaný unique guard '<credentialId|null>:<external_id>' pro DB-level vynucení invariantu (credential, external_id). Strapi v5 ukládá relace v link tabulkách, takže composite unique přes (credential, external_id) nelze vyjádřit jediným indexem; tento skalární sloupec ano. Udržuje ho service upsertAsset(); UNIQUE index nasazuje bootstrap ensureCloudAssetUniqueIndex(). NIKDY se nevrací v API (private).")
    resource_type: StrictStr = Field(description="Provider resource type as a FREE STRING (ec2 | rds | s3 | lambda | vpc | iam-user | sg | azure-vm | storage-account | gce | gcs | ...). Intentionally not an enum — too many provider-specific types to maintain.")
    provider: StrictStr
    credential: Optional[CreateAccessReviewRequestDataReviewer] = None
    organisation: Optional[CreateAccessReviewRequestDataReviewer] = None
    region: Optional[StrictStr] = Field(default=None, description="Provider region/location where the asset lives.")
    name: Optional[StrictStr] = Field(default=None, description="Human-readable name/label of the resource (provider Name tag, display name, ...).")
    tags: Optional[Any] = Field(default=None, description="Provider tags as a {k:v} map.")
    metadata: Optional[Any] = Field(default=None, description="Raw resource descriptor (instance type, IPs, SG ids, ...). LONGTEXT — do not store binary blobs.")
    ownership: Optional[StrictStr] = Field(default=None, description="Adoption state of the asset relative to Sencai management.")
    is_managed_by_sencai: Optional[StrictBool] = Field(default=None, description="True once Sencai actively manages this asset (adopted-for-management).")
    managed_as: Optional[StrictStr] = Field(default=None, description="documentId of the cloud-resource/cloud-instance this asset is adopted as, if Sencai actively manages it (nullable).")
    discovered_at: Optional[datetime] = Field(default=None, description="Timestamp when this asset was first discovered by a scan.")
    last_seen_at: Optional[datetime] = Field(default=None, description="Timestamp of the most recent scan that observed this asset (refreshed on every upsert).")
    stale: Optional[StrictBool] = Field(default=None, description="True když asset nebyl viděn posledním dokončeným scanem (last_seen_at < scan_started). Soft-flag (W3-03 scan-callback) — adopted/managed assety se NIKDY nemažou, jen flagují stale; unmanaged taky jen flagujeme (záznam zůstává pro audit/historii). Stale se zruší (false) jakmile ho další scan zase uvidí.")
    first_adopted_at: Optional[datetime] = Field(default=None, description="Timestamp when the asset was first adopted for Sencai management (nullable).")
    tag_status: Optional[StrictStr] = Field(default=None, description="Stav adopt tag-injection (W3-05). pending = tag job zařazen; tagged = Sencai adopt tagy zapsány do cloudu; noop = provider/typ tagging nepodporuje (DB-only adopce); failed = tagging API selhalo. Plní worker přes tag-callback. Nullable (zdroj nebyl nikdy adoptován pro management).")
    home_region: Optional[StrictStr] = Field(default=None, description="Logical data-residency region of the tenant (CELL invariant, F2.CELL.01).")
    cell_id: Optional[StrictStr] = Field(default=None, description="Deployment cell within home_region for blast-radius isolation (CELL invariant, F2.CELL.01).")
    __properties: ClassVar[List[str]] = ["external_id", "credential_external_id_key", "resource_type", "provider", "credential", "organisation", "region", "name", "tags", "metadata", "ownership", "is_managed_by_sencai", "managed_as", "discovered_at", "last_seen_at", "stale", "first_adopted_at", "tag_status", "home_region", "cell_id"]

    @field_validator('provider')
    def provider_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['aws', 'azure', 'gcp', 'hetzner', 'ovhcloud', 'scaleway', 'upcloud', 'digitalocean']):
            raise ValueError("must be one of enum values ('aws', 'azure', 'gcp', 'hetzner', 'ovhcloud', 'scaleway', 'upcloud', 'digitalocean')")
        return value

    @field_validator('ownership')
    def ownership_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['unmanaged', 'read-only', 'managed', 'ignored']):
            raise ValueError("must be one of enum values ('unmanaged', 'read-only', 'managed', 'ignored')")
        return value

    @field_validator('tag_status')
    def tag_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending', 'tagged', 'noop', 'failed']):
            raise ValueError("must be one of enum values ('pending', 'tagged', 'noop', 'failed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CloudAsset from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of credential
        if self.credential:
            _dict['credential'] = self.credential.to_dict()
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        # set to None if tags (nullable) is None
        # and model_fields_set contains the field
        if self.tags is None and "tags" in self.model_fields_set:
            _dict['tags'] = None

        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CloudAsset from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "external_id": obj.get("external_id"),
            "credential_external_id_key": obj.get("credential_external_id_key"),
            "resource_type": obj.get("resource_type"),
            "provider": obj.get("provider"),
            "credential": CreateAccessReviewRequestDataReviewer.from_dict(obj["credential"]) if obj.get("credential") is not None else None,
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "region": obj.get("region"),
            "name": obj.get("name"),
            "tags": obj.get("tags"),
            "metadata": obj.get("metadata"),
            "ownership": obj.get("ownership"),
            "is_managed_by_sencai": obj.get("is_managed_by_sencai"),
            "managed_as": obj.get("managed_as"),
            "discovered_at": obj.get("discovered_at"),
            "last_seen_at": obj.get("last_seen_at"),
            "stale": obj.get("stale"),
            "first_adopted_at": obj.get("first_adopted_at"),
            "tag_status": obj.get("tag_status"),
            "home_region": obj.get("home_region"),
            "cell_id": obj.get("cell_id")
        })
        return _obj


