# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Cluster(BaseModel):
    """
    Cluster
    """ # noqa: E501
    name: StrictStr
    description: Optional[StrictStr] = None
    users_permissions_user: Optional[CreateAccessReviewRequestDataReviewer] = None
    state: StrictStr
    cluster_type: Optional[StrictStr] = None
    region: Optional[StrictStr] = None
    max_services: Optional[StrictInt] = None
    current_services_count: Optional[StrictInt] = None
    monthly_cost: Optional[Union[StrictFloat, StrictInt]] = None
    metadata: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["name", "description", "users_permissions_user", "state", "cluster_type", "region", "max_services", "current_services_count", "monthly_cost", "metadata"]

    @field_validator('state')
    def state_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['active', 'inactive', 'pending', 'suspended']):
            raise ValueError("must be one of enum values ('active', 'inactive', 'pending', 'suspended')")
        return value

    @field_validator('cluster_type')
    def cluster_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['development', 'staging', 'production', 'testing', 'qa', 'integration', 'uat', 'preview', 'sandbox', 'demo', 'hotfix', 'canary', 'pre-production', 'prod-like']):
            raise ValueError("must be one of enum values ('development', 'staging', 'production', 'testing', 'qa', 'integration', 'uat', 'preview', 'sandbox', 'demo', 'hotfix', 'canary', 'pre-production', 'prod-like')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Cluster from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of users_permissions_user
        if self.users_permissions_user:
            _dict['users_permissions_user'] = self.users_permissions_user.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Cluster from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "name": obj.get("name"),
            "description": obj.get("description"),
            "users_permissions_user": CreateAccessReviewRequestDataReviewer.from_dict(obj["users_permissions_user"]) if obj.get("users_permissions_user") is not None else None,
            "state": obj.get("state"),
            "cluster_type": obj.get("cluster_type"),
            "region": obj.get("region"),
            "max_services": obj.get("max_services"),
            "current_services_count": obj.get("current_services_count"),
            "monthly_cost": obj.get("monthly_cost"),
            "metadata": obj.get("metadata")
        })
        return _obj


