# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateOrganisationMemberRequestData(BaseModel):
    """
    CreateOrganisationMemberRequestData
    """ # noqa: E501
    user: Optional[CreateAccessReviewRequestDataReviewer] = None
    organisation: CreateAccessReviewRequestDataReviewer
    role: StrictStr
    email: Optional[StrictStr] = None
    invitation_token: Optional[StrictStr] = None
    invited_at: Optional[datetime] = None
    accepted_at: Optional[datetime] = None
    invited_by: Optional[CreateAccessReviewRequestDataReviewer] = None
    home_region: StrictStr = Field(description="Logical data-residency region of the tenant (CELL invariant, F2.CELL.01)")
    cell_id: Optional[StrictStr] = Field(default=None, description="Deployment cell within home_region for blast-radius isolation (CELL invariant, F2.CELL.01)")
    __properties: ClassVar[List[str]] = ["user", "organisation", "role", "email", "invitation_token", "invited_at", "accepted_at", "invited_by", "home_region", "cell_id"]

    @field_validator('role')
    def role_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['owner', 'admin', 'member', 'viewer', 'auditor']):
            raise ValueError("must be one of enum values ('owner', 'admin', 'member', 'viewer', 'auditor')")
        return value

    @field_validator('home_region')
    def home_region_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['eu', 'us', 'apac']):
            raise ValueError("must be one of enum values ('eu', 'us', 'apac')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateOrganisationMemberRequestData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of user
        if self.user:
            _dict['user'] = self.user.to_dict()
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of invited_by
        if self.invited_by:
            _dict['invited_by'] = self.invited_by.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateOrganisationMemberRequestData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user": CreateAccessReviewRequestDataReviewer.from_dict(obj["user"]) if obj.get("user") is not None else None,
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "role": obj.get("role"),
            "email": obj.get("email"),
            "invitation_token": obj.get("invitation_token"),
            "invited_at": obj.get("invited_at"),
            "accepted_at": obj.get("accepted_at"),
            "invited_by": CreateAccessReviewRequestDataReviewer.from_dict(obj["invited_by"]) if obj.get("invited_by") is not None else None,
            "home_region": obj.get("home_region"),
            "cell_id": obj.get("cell_id")
        })
        return _obj


