# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateLegalDocumentRequestData(BaseModel):
    """
    CreateLegalDocumentRequestData
    """ # noqa: E501
    document_type: StrictStr
    version: StrictStr
    title: StrictStr
    effective_from: datetime
    summary_text: Optional[StrictStr] = None
    full_text_url: Optional[StrictStr] = None
    is_current: Optional[StrictBool] = None
    change_summary: Optional[StrictStr] = None
    requires_reacceptance: Optional[StrictBool] = None
    body: Optional[StrictStr] = Field(default=None, description="Full document body (Markdown). F3.LEGAL.01: seeded with a PLACEHOLDER pending lawyer review — see src/bootstrap.ts ensureLegalDocumentPlaceholders().")
    locale_code: Optional[StrictStr] = Field(default=None, description="F3.LEGAL.01: document language (cs/en). NOT the Strapi i18n plugin locale field (i18n is not enabled on this CT) — a plain string so cs/en variants of the same document_type+version can coexist as separate rows.")
    __properties: ClassVar[List[str]] = ["document_type", "version", "title", "effective_from", "summary_text", "full_text_url", "is_current", "change_summary", "requires_reacceptance", "body", "locale_code"]

    @field_validator('document_type')
    def document_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['terms_of_service', 'privacy_policy', 'dpa', 'acceptable_use', 'msa', 'subprocessors']):
            raise ValueError("must be one of enum values ('terms_of_service', 'privacy_policy', 'dpa', 'acceptable_use', 'msa', 'subprocessors')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateLegalDocumentRequestData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateLegalDocumentRequestData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "document_type": obj.get("document_type"),
            "version": obj.get("version"),
            "title": obj.get("title"),
            "effective_from": obj.get("effective_from"),
            "summary_text": obj.get("summary_text"),
            "full_text_url": obj.get("full_text_url"),
            "is_current": obj.get("is_current"),
            "change_summary": obj.get("change_summary"),
            "requires_reacceptance": obj.get("requires_reacceptance"),
            "body": obj.get("body"),
            "locale_code": obj.get("locale_code")
        })
        return _obj


