# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CreateAuditLogRequestData(BaseModel):
    """
    CreateAuditLogRequestData
    """ # noqa: E501
    action: StrictStr
    actor_user_id: Optional[StrictStr] = None
    actor_org_id: Optional[StrictStr] = None
    customer_scope: Optional[StrictStr] = None
    actor_org_scope: Optional[StrictStr] = None
    elevation_grant_id: Optional[StrictStr] = None
    resource_type: StrictStr
    resource_id: Optional[StrictStr] = None
    changes: Optional[Dict[str, Any]] = None
    correlation_id: Optional[StrictStr] = None
    risk_level: Optional[StrictStr] = None
    prev_hash: Optional[StrictStr] = None
    entry_hash: Optional[StrictStr] = None
    anchor_id: Optional[StrictStr] = None
    metadata: Optional[Dict[str, Any]] = None
    ip_address: Optional[StrictStr] = None
    user_agent: Optional[StrictStr] = None
    region: Optional[StrictStr] = Field(default=None, description="Data-residency region of the tenant at time of audit event (CELL invariant, F2.CELL.01)")
    cell_id: Optional[StrictStr] = Field(default=None, description="Deployment cell within the region at time of audit event (CELL invariant, F2.CELL.01)")
    __properties: ClassVar[List[str]] = ["action", "actor_user_id", "actor_org_id", "customer_scope", "actor_org_scope", "elevation_grant_id", "resource_type", "resource_id", "changes", "correlation_id", "risk_level", "prev_hash", "entry_hash", "anchor_id", "metadata", "ip_address", "user_agent", "region", "cell_id"]

    @field_validator('risk_level')
    def risk_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high', 'critical']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'critical')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CreateAuditLogRequestData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CreateAuditLogRequestData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "action": obj.get("action"),
            "actor_user_id": obj.get("actor_user_id"),
            "actor_org_id": obj.get("actor_org_id"),
            "customer_scope": obj.get("customer_scope"),
            "actor_org_scope": obj.get("actor_org_scope"),
            "elevation_grant_id": obj.get("elevation_grant_id"),
            "resource_type": obj.get("resource_type"),
            "resource_id": obj.get("resource_id"),
            "changes": obj.get("changes"),
            "correlation_id": obj.get("correlation_id"),
            "risk_level": obj.get("risk_level"),
            "prev_hash": obj.get("prev_hash"),
            "entry_hash": obj.get("entry_hash"),
            "anchor_id": obj.get("anchor_id"),
            "metadata": obj.get("metadata"),
            "ip_address": obj.get("ip_address"),
            "user_agent": obj.get("user_agent"),
            "region": obj.get("region"),
            "cell_id": obj.get("cell_id")
        })
        return _obj


