# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class CustomerHealthScore(BaseModel):
    """
    CustomerHealthScore
    """ # noqa: E501
    adoption_score: Optional[StrictInt] = None
    risk_level: Optional[StrictStr] = None
    active_features: Optional[Dict[str, Any]] = None
    last_login_days: Optional[StrictInt] = None
    cloud_instances_count: Optional[StrictInt] = None
    audit_events_30d: Optional[StrictInt] = None
    open_incidents_count: Optional[StrictInt] = None
    trend: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    calculated_at: Optional[datetime] = None
    organisation: Optional[CreateAccessReviewRequestDataReviewer] = None
    __properties: ClassVar[List[str]] = ["adoption_score", "risk_level", "active_features", "last_login_days", "cloud_instances_count", "audit_events_30d", "open_incidents_count", "trend", "notes", "calculated_at", "organisation"]

    @field_validator('risk_level')
    def risk_level_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high', 'churned']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'churned')")
        return value

    @field_validator('trend')
    def trend_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['improving', 'stable', 'declining']):
            raise ValueError("must be one of enum values ('improving', 'stable', 'declining')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomerHealthScore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomerHealthScore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "adoption_score": obj.get("adoption_score"),
            "risk_level": obj.get("risk_level"),
            "active_features": obj.get("active_features"),
            "last_login_days": obj.get("last_login_days"),
            "cloud_instances_count": obj.get("cloud_instances_count"),
            "audit_events_30d": obj.get("audit_events_30d"),
            "open_incidents_count": obj.get("open_incidents_count"),
            "trend": obj.get("trend"),
            "notes": obj.get("notes"),
            "calculated_at": obj.get("calculated_at"),
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None
        })
        return _obj


