# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FindKnowledgeNode200ResponseDataInner(BaseModel):
    """
    FindKnowledgeNode200ResponseDataInner
    """ # noqa: E501
    node_type: StrictStr
    label: StrictStr = Field(description="Human-readable identifier, e.g. 'backend:1337', 'ec2-i-abc123', 'postgres-prod'.")
    resource_id: Optional[StrictStr] = Field(default=None, description="Internal Strapi documentId or cloud provider resource ID.")
    resource_type: Optional[StrictStr] = Field(default=None, description="Strapi content-type slug or cloud resource kind, e.g. 'cloud-instance', 'organisation-member', 'dns-zone'.")
    properties: Optional[Any] = Field(default=None, description="Arbitrary key-value metadata for this node (provider, region, tags, etc.).")
    last_seen_at: Optional[datetime] = None
    is_active: Optional[StrictBool] = None
    organisation: Optional[CreateAccessReviewRequestDataReviewer] = None
    document_id: Optional[StrictStr] = Field(default=None, alias="documentId")
    id: Optional[StrictInt] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    published_at: Optional[datetime] = Field(default=None, alias="publishedAt")
    __properties: ClassVar[List[str]] = ["node_type", "label", "resource_id", "resource_type", "properties", "last_seen_at", "is_active", "organisation", "documentId", "id", "createdAt", "updatedAt", "publishedAt"]

    @field_validator('node_type')
    def node_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['service', 'resource', 'user', 'policy', 'network', 'database']):
            raise ValueError("must be one of enum values ('service', 'resource', 'user', 'policy', 'network', 'database')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FindKnowledgeNode200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        # set to None if properties (nullable) is None
        # and model_fields_set contains the field
        if self.properties is None and "properties" in self.model_fields_set:
            _dict['properties'] = None

        # set to None if published_at (nullable) is None
        # and model_fields_set contains the field
        if self.published_at is None and "published_at" in self.model_fields_set:
            _dict['publishedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FindKnowledgeNode200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "node_type": obj.get("node_type"),
            "label": obj.get("label"),
            "resource_id": obj.get("resource_id"),
            "resource_type": obj.get("resource_type"),
            "properties": obj.get("properties"),
            "last_seen_at": obj.get("last_seen_at"),
            "is_active": obj.get("is_active"),
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "documentId": obj.get("documentId"),
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "publishedAt": obj.get("publishedAt")
        })
        return _obj


