# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FindCustomerHealth200ResponseDataInner(BaseModel):
    """
    FindCustomerHealth200ResponseDataInner
    """ # noqa: E501
    organisation: Optional[CreateAccessReviewRequestDataReviewer] = None
    health_score: Optional[Union[StrictFloat, StrictInt]] = None
    usage_score: Optional[Union[StrictFloat, StrictInt]] = None
    growth_score: Optional[Union[StrictFloat, StrictInt]] = None
    feature_score: Optional[Union[StrictFloat, StrictInt]] = None
    support_score: Optional[Union[StrictFloat, StrictInt]] = None
    churn_risk: Optional[StrictStr] = None
    churn_signals: Optional[Any] = Field(default=None, description="Arbitrary JSON value (object, array, string, number, boolean, or null)")
    last_login_at: Optional[datetime] = None
    days_since_login: Optional[StrictInt] = None
    active_instances: Optional[StrictInt] = None
    open_tickets: Optional[StrictInt] = None
    nps_score: Optional[StrictInt] = None
    last_evaluated_at: Optional[datetime] = None
    csm_notes: Optional[StrictStr] = None
    document_id: Optional[StrictStr] = Field(default=None, alias="documentId")
    id: Optional[StrictInt] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    published_at: Optional[datetime] = Field(default=None, alias="publishedAt")
    __properties: ClassVar[List[str]] = ["organisation", "health_score", "usage_score", "growth_score", "feature_score", "support_score", "churn_risk", "churn_signals", "last_login_at", "days_since_login", "active_instances", "open_tickets", "nps_score", "last_evaluated_at", "csm_notes", "documentId", "id", "createdAt", "updatedAt", "publishedAt"]

    @field_validator('churn_risk')
    def churn_risk_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['low', 'medium', 'high', 'critical']):
            raise ValueError("must be one of enum values ('low', 'medium', 'high', 'critical')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FindCustomerHealth200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        # set to None if churn_signals (nullable) is None
        # and model_fields_set contains the field
        if self.churn_signals is None and "churn_signals" in self.model_fields_set:
            _dict['churn_signals'] = None

        # set to None if published_at (nullable) is None
        # and model_fields_set contains the field
        if self.published_at is None and "published_at" in self.model_fields_set:
            _dict['publishedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FindCustomerHealth200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "health_score": obj.get("health_score"),
            "usage_score": obj.get("usage_score"),
            "growth_score": obj.get("growth_score"),
            "feature_score": obj.get("feature_score"),
            "support_score": obj.get("support_score"),
            "churn_risk": obj.get("churn_risk"),
            "churn_signals": obj.get("churn_signals"),
            "last_login_at": obj.get("last_login_at"),
            "days_since_login": obj.get("days_since_login"),
            "active_instances": obj.get("active_instances"),
            "open_tickets": obj.get("open_tickets"),
            "nps_score": obj.get("nps_score"),
            "last_evaluated_at": obj.get("last_evaluated_at"),
            "csm_notes": obj.get("csm_notes"),
            "documentId": obj.get("documentId"),
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "publishedAt": obj.get("publishedAt")
        })
        return _obj


