# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class FindWorkspaceWatchdogEvent200ResponseDataInner(BaseModel):
    """
    FindWorkspaceWatchdogEvent200ResponseDataInner
    """ # noqa: E501
    organisation: CreateAccessReviewRequestDataReviewer
    workspace_tenant: Optional[CreateAccessReviewRequestDataReviewer] = None
    event_type: StrictStr
    severity: StrictStr
    actor_email: Optional[StrictStr] = None
    target_email: Optional[StrictStr] = None
    resource: Optional[StrictStr] = None
    ip_address: Optional[StrictStr] = None
    user_agent: Optional[StrictStr] = None
    raw_event: Optional[Any] = Field(default=None, description="Arbitrary JSON value (object, array, string, number, boolean, or null)")
    event_data: Optional[Any] = Field(default=None, description="Arbitrary JSON value (object, array, string, number, boolean, or null)")
    status: StrictStr
    notes: Optional[StrictStr] = None
    occurred_at: datetime
    notification_created: Optional[StrictBool] = None
    document_id: Optional[StrictStr] = Field(default=None, alias="documentId")
    id: Optional[StrictInt] = None
    created_at: Optional[datetime] = Field(default=None, alias="createdAt")
    updated_at: Optional[datetime] = Field(default=None, alias="updatedAt")
    published_at: Optional[datetime] = Field(default=None, alias="publishedAt")
    __properties: ClassVar[List[str]] = ["organisation", "workspace_tenant", "event_type", "severity", "actor_email", "target_email", "resource", "ip_address", "user_agent", "raw_event", "event_data", "status", "notes", "occurred_at", "notification_created", "documentId", "id", "createdAt", "updatedAt", "publishedAt"]

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['login_anomaly', 'bulk_download', 'external_share', 'admin_privilege_granted', 'mfa_disabled', 'account_suspended', 'password_reset', 'app_authorized', 'new_admin', 'oauth_app_added', 'user_suspended', 'login_from_new_country', 'bulk_delete']):
            raise ValueError("must be one of enum values ('login_anomaly', 'bulk_download', 'external_share', 'admin_privilege_granted', 'mfa_disabled', 'account_suspended', 'password_reset', 'app_authorized', 'new_admin', 'oauth_app_added', 'user_suspended', 'login_from_new_country', 'bulk_delete')")
        return value

    @field_validator('severity')
    def severity_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['critical', 'high', 'medium', 'low', 'info']):
            raise ValueError("must be one of enum values ('critical', 'high', 'medium', 'low', 'info')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['new', 'investigating', 'resolved', 'false_positive']):
            raise ValueError("must be one of enum values ('new', 'investigating', 'resolved', 'false_positive')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FindWorkspaceWatchdogEvent200ResponseDataInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        # override the default output from pydantic by calling `to_dict()` of workspace_tenant
        if self.workspace_tenant:
            _dict['workspace_tenant'] = self.workspace_tenant.to_dict()
        # set to None if raw_event (nullable) is None
        # and model_fields_set contains the field
        if self.raw_event is None and "raw_event" in self.model_fields_set:
            _dict['raw_event'] = None

        # set to None if event_data (nullable) is None
        # and model_fields_set contains the field
        if self.event_data is None and "event_data" in self.model_fields_set:
            _dict['event_data'] = None

        # set to None if published_at (nullable) is None
        # and model_fields_set contains the field
        if self.published_at is None and "published_at" in self.model_fields_set:
            _dict['publishedAt'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FindWorkspaceWatchdogEvent200ResponseDataInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "workspace_tenant": CreateAccessReviewRequestDataReviewer.from_dict(obj["workspace_tenant"]) if obj.get("workspace_tenant") is not None else None,
            "event_type": obj.get("event_type"),
            "severity": obj.get("severity"),
            "actor_email": obj.get("actor_email"),
            "target_email": obj.get("target_email"),
            "resource": obj.get("resource"),
            "ip_address": obj.get("ip_address"),
            "user_agent": obj.get("user_agent"),
            "raw_event": obj.get("raw_event"),
            "event_data": obj.get("event_data"),
            "status": obj.get("status"),
            "notes": obj.get("notes"),
            "occurred_at": obj.get("occurred_at"),
            "notification_created": obj.get("notification_created"),
            "documentId": obj.get("documentId"),
            "id": obj.get("id"),
            "createdAt": obj.get("createdAt"),
            "updatedAt": obj.get("updatedAt"),
            "publishedAt": obj.get("publishedAt")
        })
        return _obj


