# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class GitConnectorStatus(BaseModel):
    """
    GitConnectorStatus
    """ # noqa: E501
    instance_id: StrictStr = Field(alias="instanceId")
    gitstatus: Optional[StrictStr] = None
    last_heartbeat: Optional[datetime] = Field(default=None, alias="lastHeartbeat")
    uptime: Optional[StrictInt] = None
    version: Optional[StrictStr] = None
    toolbox_status: Optional[StrictStr] = Field(default=None, alias="toolboxStatus")
    apps_status: Optional[StrictStr] = Field(default=None, alias="appsStatus")
    total_repositories: Optional[StrictInt] = Field(default=None, alias="totalRepositories")
    toolbox_repositories: Optional[StrictInt] = Field(default=None, alias="toolboxRepositories")
    apps_repositories: Optional[StrictInt] = Field(default=None, alias="appsRepositories")
    last_sync_date: Optional[datetime] = Field(default=None, alias="lastSyncDate")
    last_error: Optional[StrictStr] = Field(default=None, alias="lastError")
    metadata: Optional[Any] = Field(default=None, description="Arbitrary JSON value (object, array, string, number, boolean, or null)")
    __properties: ClassVar[List[str]] = ["instanceId", "gitstatus", "lastHeartbeat", "uptime", "version", "toolboxStatus", "appsStatus", "totalRepositories", "toolboxRepositories", "appsRepositories", "lastSyncDate", "lastError", "metadata"]

    @field_validator('gitstatus')
    def gitstatus_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['healthy', 'unhealthy', 'turned-off']):
            raise ValueError("must be one of enum values ('healthy', 'unhealthy', 'turned-off')")
        return value

    @field_validator('toolbox_status')
    def toolbox_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['connected', 'disconnected', 'error']):
            raise ValueError("must be one of enum values ('connected', 'disconnected', 'error')")
        return value

    @field_validator('apps_status')
    def apps_status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['connected', 'disconnected', 'error']):
            raise ValueError("must be one of enum values ('connected', 'disconnected', 'error')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of GitConnectorStatus from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of GitConnectorStatus from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "instanceId": obj.get("instanceId"),
            "gitstatus": obj.get("gitstatus"),
            "lastHeartbeat": obj.get("lastHeartbeat"),
            "uptime": obj.get("uptime"),
            "version": obj.get("version"),
            "toolboxStatus": obj.get("toolboxStatus"),
            "appsStatus": obj.get("appsStatus"),
            "totalRepositories": obj.get("totalRepositories"),
            "toolboxRepositories": obj.get("toolboxRepositories"),
            "appsRepositories": obj.get("appsRepositories"),
            "lastSyncDate": obj.get("lastSyncDate"),
            "lastError": obj.get("lastError"),
            "metadata": obj.get("metadata")
        })
        return _obj


