# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class MeteringEvent(BaseModel):
    """
    MeteringEvent
    """ # noqa: E501
    event_type: StrictStr
    quantity: StrictInt
    period_start: datetime
    period_end: datetime
    idempotency_key: StrictStr
    unit: Optional[StrictStr] = None
    metadata: Optional[Any] = Field(default=None, description="Arbitrary JSON value (object, array, string, number, boolean, or null)")
    organisation: CreateAccessReviewRequestDataReviewer
    lago_synced: Optional[StrictBool] = None
    synced_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["event_type", "quantity", "period_start", "period_end", "idempotency_key", "unit", "metadata", "organisation", "lago_synced", "synced_at"]

    @field_validator('event_type')
    def event_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['managed_host_observed', 'server_patched', 'org_managed', 'cloud_instance_hour', 'llm_token_batch']):
            raise ValueError("must be one of enum values ('managed_host_observed', 'server_patched', 'org_managed', 'cloud_instance_hour', 'llm_token_batch')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MeteringEvent from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        # set to None if metadata (nullable) is None
        # and model_fields_set contains the field
        if self.metadata is None and "metadata" in self.model_fields_set:
            _dict['metadata'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MeteringEvent from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "event_type": obj.get("event_type"),
            "quantity": obj.get("quantity"),
            "period_start": obj.get("period_start"),
            "period_end": obj.get("period_end"),
            "idempotency_key": obj.get("idempotency_key"),
            "unit": obj.get("unit"),
            "metadata": obj.get("metadata"),
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "lago_synced": obj.get("lago_synced"),
            "synced_at": obj.get("synced_at")
        })
        return _obj


