# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class Nis2Gap(BaseModel):
    """
    Nis2Gap
    """ # noqa: E501
    requirement: StrictStr
    article: Optional[StrictStr] = None
    annex: StrictStr
    gap_description: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    target_date: Optional[date] = None
    owner: Optional[StrictStr] = None
    evidence_links: Optional[Any] = Field(default=None, description="Arbitrary JSON value (object, array, string, number, boolean, or null)")
    audit_action_evidence: Optional[Any] = Field(default=None, description="Arbitrary JSON value (object, array, string, number, boolean, or null)")
    organisation: Optional[CreateAccessReviewRequestDataReviewer] = None
    __properties: ClassVar[List[str]] = ["requirement", "article", "annex", "gap_description", "status", "target_date", "owner", "evidence_links", "audit_action_evidence", "organisation"]

    @field_validator('annex')
    def annex_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['annex_i', 'annex_ii', 'annex_iii']):
            raise ValueError("must be one of enum values ('annex_i', 'annex_ii', 'annex_iii')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['open', 'in_progress', 'closed', 'risk_accepted']):
            raise ValueError("must be one of enum values ('open', 'in_progress', 'closed', 'risk_accepted')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Nis2Gap from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        # set to None if evidence_links (nullable) is None
        # and model_fields_set contains the field
        if self.evidence_links is None and "evidence_links" in self.model_fields_set:
            _dict['evidence_links'] = None

        # set to None if audit_action_evidence (nullable) is None
        # and model_fields_set contains the field
        if self.audit_action_evidence is None and "audit_action_evidence" in self.model_fields_set:
            _dict['audit_action_evidence'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Nis2Gap from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "requirement": obj.get("requirement"),
            "article": obj.get("article"),
            "annex": obj.get("annex"),
            "gap_description": obj.get("gap_description"),
            "status": obj.get("status"),
            "target_date": obj.get("target_date"),
            "owner": obj.get("owner"),
            "evidence_links": obj.get("evidence_links"),
            "audit_action_evidence": obj.get("audit_action_evidence"),
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None
        })
        return _obj


