# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt
from typing import Any, ClassVar, Dict, List, Optional
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class SoftwareInventory(BaseModel):
    """
    SoftwareInventory
    """ # noqa: E501
    sencai_agent: Optional[CreateAccessReviewRequestDataReviewer] = None
    organisation: Optional[CreateAccessReviewRequestDataReviewer] = None
    packages: Optional[Dict[str, Any]] = None
    eol_findings: Optional[Dict[str, Any]] = None
    packages_count: Optional[StrictInt] = None
    eol_critical_count: Optional[StrictInt] = None
    eol_warning_count: Optional[StrictInt] = None
    collected_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["sencai_agent", "organisation", "packages", "eol_findings", "packages_count", "eol_critical_count", "eol_warning_count", "collected_at"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SoftwareInventory from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of sencai_agent
        if self.sencai_agent:
            _dict['sencai_agent'] = self.sencai_agent.to_dict()
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SoftwareInventory from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "sencai_agent": CreateAccessReviewRequestDataReviewer.from_dict(obj["sencai_agent"]) if obj.get("sencai_agent") is not None else None,
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "packages": obj.get("packages"),
            "eol_findings": obj.get("eol_findings"),
            "packages_count": obj.get("packages_count"),
            "eol_critical_count": obj.get("eol_critical_count"),
            "eol_warning_count": obj.get("eol_warning_count"),
            "collected_at": obj.get("collected_at")
        })
        return _obj


