# coding: utf-8

"""
    Sencai Platform API

    Consolidated OpenAPI 3.x specification for the Sencai platform backend (`/api/v1/*`). Covers auto-discovered CRUD content-types plus hand-documented custom routes. See `openapi/README.md` for regeneration instructions and versioning/deprecation policy (`SUNSET_DATE` env convention, see doc.sencai.space/dev/api-versioning).

    The version of the OpenAPI document: 1.0.0
    Contact: api@sencai.space
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictFloat, StrictInt, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional, Union
from sencai_sdk.models.create_access_review_request_data_reviewer import CreateAccessReviewRequestDataReviewer
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class WorkloadProfile(BaseModel):
    """
    WorkloadProfile
    """ # noqa: E501
    instance_id: Optional[StrictStr] = Field(default=None, description="documentId of the source cloud-instance record")
    instance_name: Optional[StrictStr] = None
    profile_type: StrictStr
    peak_hours: Optional[Dict[str, Any]] = Field(default=None, description="Array of hour integers (0-23) when CPU/memory is high")
    idle_hours: Optional[Dict[str, Any]] = Field(default=None, description="Array of hour integers (0-23) when instance is underutilised")
    avg_cpu_pct: Optional[Union[StrictFloat, StrictInt]] = None
    avg_memory_pct: Optional[Union[StrictFloat, StrictInt]] = None
    current_instance_type: Optional[StrictStr] = Field(default=None, description="Current instance type e.g. m5.2xlarge")
    migration_target: Optional[StrictStr] = Field(default=None, description="Recommended target instance type e.g. m5.xlarge")
    estimated_monthly_savings_usd: Optional[Union[StrictFloat, StrictInt]] = None
    confidence: Optional[Union[StrictFloat, StrictInt]] = None
    analysis_model: Optional[StrictStr] = None
    recommendation_summary: Optional[StrictStr] = None
    status: Optional[StrictStr] = None
    organisation: Optional[CreateAccessReviewRequestDataReviewer] = None
    profiled_at: Optional[datetime] = None
    __properties: ClassVar[List[str]] = ["instance_id", "instance_name", "profile_type", "peak_hours", "idle_hours", "avg_cpu_pct", "avg_memory_pct", "current_instance_type", "migration_target", "estimated_monthly_savings_usd", "confidence", "analysis_model", "recommendation_summary", "status", "organisation", "profiled_at"]

    @field_validator('profile_type')
    def profile_type_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['cpu_bound', 'memory_bound', 'io_bound', 'idle', 'mixed']):
            raise ValueError("must be one of enum values ('cpu_bound', 'memory_bound', 'io_bound', 'idle', 'mixed')")
        return value

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['pending_review', 'accepted', 'implemented', 'dismissed']):
            raise ValueError("must be one of enum values ('pending_review', 'accepted', 'implemented', 'dismissed')")
        return value

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of WorkloadProfile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of organisation
        if self.organisation:
            _dict['organisation'] = self.organisation.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of WorkloadProfile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "instance_id": obj.get("instance_id"),
            "instance_name": obj.get("instance_name"),
            "profile_type": obj.get("profile_type"),
            "peak_hours": obj.get("peak_hours"),
            "idle_hours": obj.get("idle_hours"),
            "avg_cpu_pct": obj.get("avg_cpu_pct"),
            "avg_memory_pct": obj.get("avg_memory_pct"),
            "current_instance_type": obj.get("current_instance_type"),
            "migration_target": obj.get("migration_target"),
            "estimated_monthly_savings_usd": obj.get("estimated_monthly_savings_usd"),
            "confidence": obj.get("confidence"),
            "analysis_model": obj.get("analysis_model"),
            "recommendation_summary": obj.get("recommendation_summary"),
            "status": obj.get("status"),
            "organisation": CreateAccessReviewRequestDataReviewer.from_dict(obj["organisation"]) if obj.get("organisation") is not None else None,
            "profiled_at": obj.get("profiled_at")
        })
        return _obj


